### Create sensor one
POST http://localhost:8081/sensor
Content-Type: application/json

{
  "name": "Sensor1",
  "location": "Living Room",
  "active": true,
  "type": "INDOOR"
}

### Retrieve the sensor
GET http://localhost:8081/sensor

### Create a new Measurement
POST http://localhost:8081/measurements
Content-Type: application/json

{
  "timestamp": "2024-11-01T12:30:00",
  "temperature": 50.0,
  "humidity": 22.2,
  "sensor": {
    "id": 1
  }
}

### Receive all measurements from sensor 1
GET http://localhost:8081/measurements/sensor/1

### Update a measurement
PUT http://localhost:8081/measurements/17
Content-Type: application/json

{
  "timestamp": "2024-11-07T12:00:00Z",
  "temperature": 80.5,
  "humidity": 99.0
}

### Swagger
http://localhost:8082/swagger-ui/index.html