### Create sensor one
POST http://localhost:50714/sensormodule/sensor
Content-Type: application/json

{
  "name": "Sensor1",
  "location": "Living Room",
  "active": true,
  "type": "INDOOR"
}

### Retrieve all sensors
GET http://localhost:49177/sensormodule/sensor

### Create a new measurement on sensor one
POST http://localhost:8080/sensormodule/measurements
Content-Type: application/json

{
  "timestamp": "2024-11-01T12:30:00",
  "temperature": 50.0,
  "humidity": 22.2,
  "sensor": {
    "id": 1
  }
}

### Receive all measurements from sensor one
GET http://localhost:8080/sensormodule/measurements/sensor/1

### Update a measurement
PUT http://localhost:8080/sensormodule/measurements/2
Content-Type: application/json

{
  "timestamp": "2024-11-07T12:00:00Z",
  "temperature": 80.5,
  "humidity": 99.0
}


### Delete all measures of sensor 1
DELETE http://localhost:8080/sensormodule/measurements/sensor/1


### Usage of the Spring Boot Actuator
http://localhost:8080/actuator

### Usage of the Spring Boot Actuator - health
http://localhost:8080/actuator/health

### Usage of the Spring Boot Actuator - info
http://localhost:8080/actuator/info

